name: Terraform Plan

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}



jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: environment
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: |
            {
              "clientId": "${{ env.ARM_CLIENT_ID }}",
              "clientSecret": "${{ env.ARM_CLIENT_SECRET }}",
              "subscriptionId": "${{ env.ARM_SUBSCRIPTION_ID }}",
              "tenantId": "${{ env.ARM_TENANT_ID }}"
            }

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: |
          terraform plan -out tfplan
      
      - name: Terraform Plan
        run: |
        
      
      - name: Terraform Show JSON
        run: |
          terraform show -json tfplan > terraform_plan_summary.json
          status=$?
          
          echo "terraform show exit code: $status"
          echo "file size: $(wc -c < terraform_plan_summary.json) bytes"
          
          if [ "$status" -ne 0 ]; then
            exit "$status"
          fi
          
          jq empty terraform_plan_summary.json
                   
         # > terraform_plan_summary.json && cat terraform_plan_summary.json &&  bash ./summary.sh
    

