name: Terraform Plan

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}



jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: |
            {
              "clientId": "${{ env.ARM_CLIENT_ID }}",
              "clientSecret": "${{ env.ARM_CLIENT_SECRET }}",
              "subscriptionId": "${{ env.ARM_SUBSCRIPTION_ID }}",
              "tenantId": "${{ env.ARM_TENANT_ID }}"
            }

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3

      - name: Terraform Init
        working-directory: environment
        run: terraform init

      - name: Terraform Plan
        working-directory: environment
        run: |
          terraform plan \
            -out="${{ github.workspace }}/.github/script/tfplan"
      
      - name: Terraform Show JSON
        working-directory: environment
        shell: bash
        run: |
         terraform show -json tfplan  > ../.github/script/terraform_plan_summary.json
      
      - name: Validate JSON
        working-directory: .github/script
        shell: bash
        run: |
          jq empty terraform_plan_summary.json
          echo "JSON is valid"
      
      - name: Run Summary Script
        working-directory: .github/script
        shell: bash
        run: |
          ./summary.sh

